### ISSUE TITLE
go-ldap panic on arm devices

### ISSUE THREAD

**Issue by salmanisd** [i-core/werther#10]
**Describe the bug**
werther uses go-ldap v2 which has problems running on my arm device giving error like
`level":"info","ts":1586183401.5116482,"caller":"rlog@v1.0.0/rlog.go:43","msg":"New request","requestID":"92f290e1-fe52-4a48-88ce-238ffeb71372","method":"POST","url":"/auth/login?login_challenge=c4d68ac1df8e41ad9436f5f23476f9d0"}
2020/04/06 14:30:01 ldap: recovered panic in processMessages: runtime error: invalid memory address or nil pointer dereference
{"level":"info","ts":1586183401.5147185,"caller":"identp/identp.go:181","msg":"Failed to authenticate a login request via the OAuth2 provider","requestID":"92f290e1-fe52-4a48-88ce-238ffeb71372","error":"failed to login to a LDAP woth a service account: LDAP Result Code 200 \"Network Error\": ldap: response channel closed","errorVerbose":"LDAP Result Code 200 \"Network Error\": ldap: response channel closed\nfailed to login ...`

**To Reproduce**
run current version of werther on an arm device and try to do an ldap auth request through Login page

**Additional context**
This is common issue caused by go-ldap v2 and can be fixed by updating werther to use go-ldap v3.

for reference similar issues are following
https://github.com/hashicorp/vault/issues/6135
https://github.com/portainer/portainer/issues/3244
https://github.com/go-ldap/ldap/issues/195

**Comment by nikolaas** [comment]
@salmanisd, hello.

Can you update the go-ldap dependency and test on your arm device? PR is welcome)

**Comment by nikolaas** [comment]
@salmanisd, thank you for your contribution.
