### ISSUE TITLE
Support clients needing roles claim containing a single list

### ISSUE THREAD

**Issue by haslersn** [i-core/werther#14]
**Is your feature request related to a problem? Please describe.**
The readme describes that the role claim generated by werther has the following format:

```
{
    "https://github.com/i-core/werther/claims/roles": {
        "App1": ["role1", "role2"],
    }
}
```

However, I believe that there exist several apps that need the following format instead:

```
{
    "https://github.com/i-core/werther/claims/roles": ["role1", "role2"]
}
```

**Describe the solution you'd like**
I am not sure whether the following is the best solution, but I propose the following. For each app (e.g. `App1`), also add a claim

```
{
    "https://github.com/i-core/werther/claims/roles/App1": ["role1", "role2"]
}
```

**Describe alternatives you've considered**

* Or just flatten the roles dictionary.
* Or use a different _scope_ for each app.

**Additional context**

I'm trying to set up Kantega SSO for Confluence, using the OpenID Connect protocol.

**Comment by haslersn** [comment]
I am willing to contribute the solution myself. We should now discuss first which of the proposed solutions we want!

**Comment by haslersn** [comment]
Ping @nikolaas

**Comment by haslersn** [comment]
Something additional to consider: RedHat's 389 Directory Server stores groups in a flat structure in the following format:

```
dn: cn=GROUPNAME,ou=Groups,dc=example,dc=com
changetype: add
objectClass: top
objectClass: posixGroup
objectClass: groupOfUniqueNames
gidNumber: 12345
cn: GROUPNAME
# uniqueMember: <DN of member>
```

While werther already seems to somewhat support this (see in the code: `"(&(objectClass=groupOfUniqueNames)(uniqueMember=%[1]s))"`), there are no OUs that represent an app in 389. I think we can support 389 (and probably any other directory using the same scheme: RFC2307bis) by adding a config flag to have a flat structure of groups. This would also solve this issue #14 for such directory servers.

**Comment by nikolaas** [comment]
@haslersn, hello. 

To solve the problem with the flat structure of LDAP groups I suggest the next:

1) Add parameter FLATTEN_GROUP_PREFIX (or something like this). It should contain a CN prefix for LDAP groups which Werther will consider as groups with user roles.
2) All groups which are matched for the parameter FLATTEN_GROUP_PREFIX should contain the attribute "description" in the next format: "appname:rolename".

Thus, we can build the role claims with the structure as before.
For example, imagine we have the next groups in LDAP:

```
dn: cn=werther-app1-role1,ou=Groups,dc=example,dc=com
objectClass: groupOfUniqueNames
cn: werther-app1-role1
description: App1:role1

dn: cn=werther-app1-role2,ou=Groups,dc=example,dc=com
objectClass: groupOfUniqueNames
cn: werther-app1-role2
description: App1:role2

dn: cn=werther-app2-role1,ou=Groups,dc=example,dc=com
objectClass: groupOfUniqueNames
cn: werther-app2-role1
description: App2:role1

dn: cn=werther-app2-role2,ou=Groups,dc=example,dc=com
objectClass: groupOfUniqueNames
cn: werther-app2-role2
description: App2:role2

dn: cn=some-group,ou=Groups,dc=example,dc=com
objectClass: groupOfUniqueNames
cn: some-group
```

If we start Werther with the parameter `FLATTEN_GROUP_PREFIX=werther-` Werther will return the next roles:
```
{
    "https://github.com/i-core/werther/claims/roles": {
        "App1": ["role1", "role2"],
        "App2": ["role1", "role2"],
    }
}
```

If it solves your problem I will implement this feature in the near future.

As for making the role claim flatten, we think its structure should not depend on the implementation of LDAP. It will only complicate using of Werther and make the codebase of Werther more confusing.

**Comment by haslersn** [comment]
Your proposal doesn't quite fix the problem with 389 (or any other RFC2307bis directory), because normally they don't have such a description. It would be difficult to use Werther with an existing directory, because all the descriptions would need to be changed.

Regarding the flat role claim: I don't know any client app that needs the role claim in the format which Werther uses. I guess you know such a client app; which is it? I think usually client apps need a flat list instead.

**Comment by konstlepa** [comment]
Hi, @haslersn 👋

> Your proposal doesn't quite fix the problem with 389 (or any other RFC2307bis directory), because normally they don't have such a description. It would be difficult to use Werther with an existing directory, because all the descriptions would need to be changed.

So, there is no description or any other custom attribute... We'll test Werther on 389 DS and ponder the solution to this problem.

> Regarding the flat role claim: I don't know any client app that needs the role claim in the format which Werther uses. I guess you know such a client app; which is it? I think usually client apps need a flat list instead.

We don't see any benefits from changing the role claim's format. Only the structure in 389 DS has meaning for resolving this issue. Anyway, we'll add support of 389 DS without breaking backward compatibility. Thanks for your issue 👍

**Comment by haslersn** [comment]
Maybe we should create a different issue for the 389 DS support, because this issue right here is mainly about a different problem:

The problem is that all apps which I tried expect the roles claim to be an **array of strings**. Examples of such apps are:

- Argo CD
- CodiMD / HedgeDoc
- Kantega SSO
- Kubernetes API Server

  Reference: https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuring-the-api-server

  > JWT claim to use as the user's group. If the claim is present it must be an array of strings.
