### ISSUE TITLE
Where is 3000 located

### ISSUE THREAD

**Issue by robbietree8** [i-core/werther#17]
Hello, I'm trying to run this using docker-compose, but I was failed because 3000 port is not found anywhere.
So where is the react app located, should I build my own?

**Comment by nikolaas** [comment]
Hi, @robbietree8 👋

The docker-compose file in README.md doesn't contain frontend or backend applications. It deploys only OpenLDAP (port 389), Werther (port 8080), and Hydra (ports 4444 and 4445). There are no other exposed ports including 3000. So you are right: you should build your own react application.

In the near future, I am going to add an example including frontend and backend applications. Please see #15 to track the status.

**Comment by robbietree8** [comment]
@nikolaas thanks for your comment, I'm clear now.
