### ISSUE TITLE
searchUserRoles only search for objectClass=group

### ISSUE THREAD

**Issue by ecb34** [i-core/werther#4]
the objectClass for the roles is hardcoded and doesn't find the roles for objectClass=groupofnames | groupOfUniqueNames

![imagen](https://user-images.githubusercontent.com/26570009/67489280-99961d00-f671-11e9-83b9-3276427b37f1.png)
in ldapclient.go

**Comment by haslersn** [comment]
It also doesn't support `(&(objectClass=organizationalRole)(roleOccupant=%[1]s))`.
